name: "Build, Test and Upload"

on:
  workflow_call:
    inputs:
      upload-artifacts:
        type: boolean
        default: false
      artifact-retention:
        type: number
        default: 0
      publish-to-maven:
        type: boolean
        default: false
      java-version:
        type: number
        default: 17
      java-distribution:
        type: string
        default: "temurin"
      release-type:
        type: string
        default: "snapshot"
      check-datagen:
        type: boolean
        default: true
      datagen-folder:
        type: string
        default: ""

    secrets:
      MAVEN_PASSWORD:
        required: false

    outputs:
      modid:
        value: ${{ jobs.build.outputs.modid }}
      version:
        value: ${{ jobs.build.outputs.version }}
      summary:
        value: ${{ jobs.build.outputs.summary }}


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ inputs.release-type }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up JDK ${{ inputs.java-version }}"
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: "Setup Build"
        run: chmod 777 gradlew

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
        id: setup
        with:
          arguments: setupGithubActions

      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2
        id: build
        with:
          arguments: build

      - name: "Test with Gradle"
        uses: gradle/gradle-build-action@v2
        id: test
        with:
          arguments: runGameTestServer

      - name: "Run datagen with Gradle"
        uses: gradle/gradle-build-action@v2
        if: ${{ inputs.check-datagen }}
        id: datagen
        with:
          arguments: runData

      - name: "Check for datagen Changes"
        if: ${{ inputs.check-datagen }}
        id: check-data
        run: |
          changes_diff=$(git diff --ignore-space-at-eol --text ${{ inputs.datagen-folder }} | wc -l)
          changes_status=$(git status --porcelain ${{ inputs.datagen-folder }} | wc -l)
          changes=$(( $changes_diff + $changes_status ))
          if [ "$changes" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text ${{ inputs.datagen-folder }}
            git status ${{ inputs.datagen-folder }}
            exit 1
          fi

      - name: "Publish with Gradle"
        uses: gradle/gradle-build-action@v2
        if: ${{ inputs.publish-to-maven }}
        id: publish
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        with:
          arguments: publish

      - name: "Read summary"
        id: summary
        uses: juliangruber/read-file-action@v1
        with:
          path: summary.txt

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v3
        if: ${{ inputs.upload-artifacts }}
        with:
          name: build-artifacts
          path: build/libs/
          if-no-files-found: error
          retention-days: ${{ inputs.artifact-retention }}

      - name: "Upload Changelog"
        uses: actions/upload-artifact@v3
        if: ${{ inputs.upload-artifacts }}
        with:
          name: changelog
          path: changelog.md
          if-no-files-found: error

    outputs:
      modid: ${{ steps.setup.outputs.modid }}
      version: ${{ steps.setup.outputs.version }}
      summary: ${{ steps.summary.outputs.content }}
