name: "Publish"

on:
  workflow_call:
    inputs:
      java-version:
        type: number
        default: 17
      platform:
        type: string
        required: true
      modid:
        type: string
        required: true
      version:
        type: string
        required: true

    secrets:
      GH_TOKEN:
        required: false
      CF_API_TOKEN:
        required: false
      MODRINTH_TOKEN:
        required: false

    outputs:
      modrinth-id:
        value: ${{ jobs.publish.outputs.modrinth-id }}
      modrinth-version:
        value: ${{ jobs.publish.outputs.modrinth-version }}
      modrinth-url:
        value: ${{ jobs.publish.outputs.modrinth-url }}
      modrinth-files:
        value: ${{ jobs.publish.outputs.modrinth-files }}
      curseforge-id:
        value: ${{ jobs.publish.outputs.curseforge-id }}
      curseforge-version:
        value: ${{ jobs.publish.outputs.curseforge-version }}
      curseforge-url:
        value: ${{ jobs.publish.outputs.curseforge-url }}
      curseforge-files:
        value: ${{ jobs.publish.outputs.curseforge-files }}
      github-repo:
        value: ${{ jobs.publish.outputs.github-repo }}
      github-tag:
        value: ${{ jobs.publish.outputs.github-tag }}
      github-url:
        value: ${{ jobs.publish.outputs.github-url }}
      github-files:
        value: ${{ jobs.publish.outputs.github-files }}

jobs:
  publish:
    name: Publish to ${{ inputs.platform }}
    runs-on: ubuntu-latest

    steps:
      - name: "Download Build Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: artifacts/

      - name: "Download Changelog"
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Publish to ${{ inputs.platform }}
        id: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          java: ${{ inputs.java-version }}
          changelog-file: changelog.md
          name: ${{ inputs.modid }}-${{ inputs.version }}
          github-token: ${{ inputs.platform == 'GitHub' && secrets.GH_TOKEN || '${undefined}' }}
          curseforge-token: ${{ inputs.platform == 'CurseForge' && secrets.CF_API_TOKEN || '${undefined}' }}
          modrinth-token: ${{ inputs.platform == 'Modrinth' && secrets.MODRINTH_TOKEN || '${undefined}' }}
          files: |
            artifacts/!(*-@(all|api|deobf|slim|sources|javadoc)).jar
            artifacts/*-@(all|api|deobf|slim|sources|javadoc).jar

    outputs:
      modrinth-id: ${{ steps.publish.outputs.modrinth-id }}
      modrinth-version: ${{ steps.publish.outputs.modrinth-version }}
      modrinth-url: ${{ steps.publish.outputs.modrinth-url }}
      modrinth-files: ${{ steps.publish.outputs.modrinth-files }}
      curseforge-id: ${{ steps.publish.outputs.curseforge-id }}
      curseforge-version: ${{ steps.publish.outputs.curseforge-version }}
      curseforge-url: ${{ steps.publish.outputs.curseforge-url }}
      curseforge-files: ${{ steps.publish.outputs.curseforge-files }}
      github-repo: ${{ steps.publish.outputs.github-repo }}
      github-tag: ${{ steps.publish.outputs.github-tag }}
      github-url: ${{ steps.publish.outputs.github-url }}
      github-files: ${{ steps.publish.outputs.github-files }}
