name: "Publish"

on:
  workflow_call:
    inputs:
      java-version:
        type: number
        default: 17
      platform:
        type: string
        required: true
      modid:
        type: string
        required: true
      version:
        type: string
        required: true

    secrets:
      GITHUB_PUBLISH_TOKEN:
        required: false
      CF_API_TOKEN:
        required: false
      MODRINTH_TOKEN:
        required: false

    outputs:
      modrinth-id:
        value: ${{ jobs.publish.outputs.modrinth-id }}
      modrinth-version:
        value: ${{ jobs.publish.outputs.modrinth-version }}
      modrinth-url:
        value: ${{ jobs.publish.outputs.modrinth-url }}
      modrinth-files:
        value: ${{ jobs.publish.outputs.modrinth-files }}
      curseforge-id:
        value: ${{ jobs.publish.outputs.curseforge-id }}
      curseforge-version:
        value: ${{ jobs.publish.outputs.curseforge-version }}
      curseforge-url:
        value: ${{ jobs.publish.outputs.curseforge-url }}
      curseforge-files:
        value: ${{ jobs.publish.outputs.curseforge-files }}
      github-repo:
        value: ${{ jobs.publish.outputs.github-repo }}
      github-tag:
        value: ${{ jobs.publish.outputs.github-tag }}
      github-url:
        value: ${{ jobs.publish.outputs.github-url }}
      github-files:
        value: ${{ jobs.publish.outputs.github-files }}

jobs:
  publish:
    name: Publish to ${{ inputs.platform }}
    runs-on: ubuntu-latest

    steps:
      - name: "Download Build Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/

      - name: "Download Changelog"
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: "Publish to GitHub"
        id: publish-github
        if: ${{ inputs.platform == 'GitHub' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          java: ${{ inputs.java-version }}
          changelog-file: changelog.md
          name: ${{ inputs.modid }}-${{ inputs.version }}
          github-token: ${{ secrets.GITHUB_PUBLISH_TOKEN }}
          github-files: |
            build/libs/!(*-@(all|api|deobf|slim|sources|javadoc)).jar
            build/libs/*-@(all|api|deobf|slim|sources|javadoc).jar

      - name: "Publish to CurseForge"
        id: publish-curseforge
        if: ${{ inputs.platform == 'CurseForge' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          java: ${{ inputs.java-version }}
          changelog-file: changelog.md
          name: ${{ inputs.modid }}-${{ inputs.version }}
          files: build/libs/!(*-@(all|api|deobf|slim|sources|javadoc)).jar
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

      - name: "Publish to Modrinth"
        id: publish-modrinth
        if: ${{ inputs.platform == 'Modrinth' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          java: ${{ inputs.java-version }}
          changelog-file: changelog.md
          name: ${{ inputs.modid }}-${{ inputs.version }}
          files: build/libs/!(*-@(all|api|deobf|slim|sources|javadoc)).jar
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

    outputs:
      modrinth-id: ${{ steps.publish-modrinth.outputs.modrinth-id }}
      modrinth-version: ${{ steps.publish-modrinth.outputs.modrinth-version }}
      modrinth-url: ${{ steps.publish-modrinth.outputs.modrinth-url }}
      modrinth-files: ${{ steps.publish-modrinth.outputs.modrinth-files }}
      curseforge-id: ${{ steps.publish-curseforge.outputs.curseforge-id }}
      curseforge-version: ${{ steps.publish-curseforge.outputs.curseforge-version }}
      curseforge-url: ${{ steps.publish-curseforge.outputs.curseforge-url }}
      curseforge-files: ${{ steps.publish-curseforge.outputs.curseforge-files }}
      github-repo: ${{ steps.publish-github.outputs.github-repo }}
      github-tag: ${{ steps.publish-github.outputs.github-tag }}
      github-url: ${{ steps.publish-github.outputs.github-url }}
      github-files: ${{ steps.publish-github.outputs.github-files }}
