name: "Test Discord Notification"

on:
  workflow_dispatch: 
    inputs: 
      ping:
        description: The user or role id to ping
        type: string
        required: true
      version:
        description: The version for the notification
        type: string
        required: false
        default: 1.0-test
      summary:
        description: The summary for the notification
        type: string
        required: false
        default: Test summary

jobs:
  notify-discord:
    uses: MinecraftschurliMods/.github/.github/workflows/notify_discord.yml@main
    with:
      project_name: ${{ github.event.repository.name }}
      version: ${{ inputs.version }}
      summary: ${{ inputs.summary }}
      curseforge_url: https://www.curseforge.com/minecraft/mc-mods/ars-magica-legacy
      modrinth_url: https://modrinth.com/mod/ars-magica-legacy
      github_url: https://github.com/MinecraftschurliMods/Ars-Magica-Legacy
      logo_url: https://raw.githubusercontent.com/MinecraftschurliMods/Ars-Magica-Legacy/version/1.19.x/src/main/resources/logo_small.png
      update_ping: ${{ inputs.ping }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_TEST_WEBHOOK }}
